/*
VPN API

Description of the VPN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vpn

import (
	"encoding/json"
)

// checks if the VpnCoreGet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpnCoreGet{}

// VpnCoreGet struct for VpnCoreGet
type VpnCoreGet struct {
	Spec *Spec `json:"spec,omitempty"`
	State *State `json:"state,omitempty"`
	UpdateAvailable *bool `json:"updateAvailable,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewVpnCoreGet instantiates a new VpnCoreGet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpnCoreGet() *VpnCoreGet {
	this := VpnCoreGet{}
	var updateAvailable bool = false
	this.UpdateAvailable = &updateAvailable
	return &this
}

// NewVpnCoreGetWithDefaults instantiates a new VpnCoreGet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpnCoreGetWithDefaults() *VpnCoreGet {
	this := VpnCoreGet{}
	var updateAvailable bool = false
	this.UpdateAvailable = &updateAvailable
	return &this
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *VpnCoreGet) GetSpec() Spec {
	if o == nil || IsNil(o.Spec) {
		var ret Spec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpnCoreGet) GetSpecOk() (*Spec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *VpnCoreGet) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given Spec and assigns it to the Spec field.
func (o *VpnCoreGet) SetSpec(v Spec) {
	o.Spec = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *VpnCoreGet) GetState() State {
	if o == nil || IsNil(o.State) {
		var ret State
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpnCoreGet) GetStateOk() (*State, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *VpnCoreGet) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given State and assigns it to the State field.
func (o *VpnCoreGet) SetState(v State) {
	o.State = &v
}

// GetUpdateAvailable returns the UpdateAvailable field value if set, zero value otherwise.
func (o *VpnCoreGet) GetUpdateAvailable() bool {
	if o == nil || IsNil(o.UpdateAvailable) {
		var ret bool
		return ret
	}
	return *o.UpdateAvailable
}

// GetUpdateAvailableOk returns a tuple with the UpdateAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpnCoreGet) GetUpdateAvailableOk() (*bool, bool) {
	if o == nil || IsNil(o.UpdateAvailable) {
		return nil, false
	}
	return o.UpdateAvailable, true
}

// HasUpdateAvailable returns a boolean if a field has been set.
func (o *VpnCoreGet) HasUpdateAvailable() bool {
	if o != nil && !IsNil(o.UpdateAvailable) {
		return true
	}

	return false
}

// SetUpdateAvailable gets a reference to the given bool and assigns it to the UpdateAvailable field.
func (o *VpnCoreGet) SetUpdateAvailable(v bool) {
	o.UpdateAvailable = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *VpnCoreGet) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpnCoreGet) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *VpnCoreGet) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *VpnCoreGet) SetName(v string) {
	o.Name = &v
}

func (o VpnCoreGet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpnCoreGet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.UpdateAvailable) {
		toSerialize["updateAvailable"] = o.UpdateAvailable
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableVpnCoreGet struct {
	value *VpnCoreGet
	isSet bool
}

func (v NullableVpnCoreGet) Get() *VpnCoreGet {
	return v.value
}

func (v *NullableVpnCoreGet) Set(val *VpnCoreGet) {
	v.value = val
	v.isSet = true
}

func (v NullableVpnCoreGet) IsSet() bool {
	return v.isSet
}

func (v *NullableVpnCoreGet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpnCoreGet(val *VpnCoreGet) *NullableVpnCoreGet {
	return &NullableVpnCoreGet{value: val, isSet: true}
}

func (v NullableVpnCoreGet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpnCoreGet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


