/*
API Manager Policy API

API Manager Policy API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim_policy

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApimOutboundPolicyBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApimOutboundPolicyBody{}

// ApimOutboundPolicyBody Request body for creating an outbound policy. Differs from `ApimPolicyBody` in two ways: it carries `apiVersionId` + `upstreamIds` (required, one or more upstream identifiers), and it does NOT carry `pointcutData` — outbound policies apply at the upstream binding level rather than via URL pointcuts. 
type ApimOutboundPolicyBody struct {
	ConfigurationData map[string]interface{} `json:"configurationData"`
	// The numeric API instance id (same as `apiId` in `ApimPolicy`).
	ApiVersionId int32 `json:"apiVersionId"`
	GroupId string `json:"groupId"`
	AssetId string `json:"assetId"`
	AssetVersion string `json:"assetVersion"`
	Label NullableString `json:"label,omitempty"`
	// Upstream identifiers (UUID strings) the policy must bind to. The API creates one policy record per id and returns them all in the response array. 
	UpstreamIds []string `json:"upstreamIds"`
}

type _ApimOutboundPolicyBody ApimOutboundPolicyBody

// NewApimOutboundPolicyBody instantiates a new ApimOutboundPolicyBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApimOutboundPolicyBody(configurationData map[string]interface{}, apiVersionId int32, groupId string, assetId string, assetVersion string, upstreamIds []string) *ApimOutboundPolicyBody {
	this := ApimOutboundPolicyBody{}
	this.ConfigurationData = configurationData
	this.ApiVersionId = apiVersionId
	this.GroupId = groupId
	this.AssetId = assetId
	this.AssetVersion = assetVersion
	this.UpstreamIds = upstreamIds
	return &this
}

// NewApimOutboundPolicyBodyWithDefaults instantiates a new ApimOutboundPolicyBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApimOutboundPolicyBodyWithDefaults() *ApimOutboundPolicyBody {
	this := ApimOutboundPolicyBody{}
	return &this
}

// GetConfigurationData returns the ConfigurationData field value
func (o *ApimOutboundPolicyBody) GetConfigurationData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ConfigurationData
}

// GetConfigurationDataOk returns a tuple with the ConfigurationData field value
// and a boolean to check if the value has been set.
func (o *ApimOutboundPolicyBody) GetConfigurationDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.ConfigurationData, true
}

// SetConfigurationData sets field value
func (o *ApimOutboundPolicyBody) SetConfigurationData(v map[string]interface{}) {
	o.ConfigurationData = v
}

// GetApiVersionId returns the ApiVersionId field value
func (o *ApimOutboundPolicyBody) GetApiVersionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ApiVersionId
}

// GetApiVersionIdOk returns a tuple with the ApiVersionId field value
// and a boolean to check if the value has been set.
func (o *ApimOutboundPolicyBody) GetApiVersionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiVersionId, true
}

// SetApiVersionId sets field value
func (o *ApimOutboundPolicyBody) SetApiVersionId(v int32) {
	o.ApiVersionId = v
}

// GetGroupId returns the GroupId field value
func (o *ApimOutboundPolicyBody) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *ApimOutboundPolicyBody) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *ApimOutboundPolicyBody) SetGroupId(v string) {
	o.GroupId = v
}

// GetAssetId returns the AssetId field value
func (o *ApimOutboundPolicyBody) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *ApimOutboundPolicyBody) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *ApimOutboundPolicyBody) SetAssetId(v string) {
	o.AssetId = v
}

// GetAssetVersion returns the AssetVersion field value
func (o *ApimOutboundPolicyBody) GetAssetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetVersion
}

// GetAssetVersionOk returns a tuple with the AssetVersion field value
// and a boolean to check if the value has been set.
func (o *ApimOutboundPolicyBody) GetAssetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetVersion, true
}

// SetAssetVersion sets field value
func (o *ApimOutboundPolicyBody) SetAssetVersion(v string) {
	o.AssetVersion = v
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApimOutboundPolicyBody) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApimOutboundPolicyBody) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *ApimOutboundPolicyBody) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *ApimOutboundPolicyBody) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *ApimOutboundPolicyBody) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *ApimOutboundPolicyBody) UnsetLabel() {
	o.Label.Unset()
}

// GetUpstreamIds returns the UpstreamIds field value
func (o *ApimOutboundPolicyBody) GetUpstreamIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.UpstreamIds
}

// GetUpstreamIdsOk returns a tuple with the UpstreamIds field value
// and a boolean to check if the value has been set.
func (o *ApimOutboundPolicyBody) GetUpstreamIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpstreamIds, true
}

// SetUpstreamIds sets field value
func (o *ApimOutboundPolicyBody) SetUpstreamIds(v []string) {
	o.UpstreamIds = v
}

func (o ApimOutboundPolicyBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApimOutboundPolicyBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["configurationData"] = o.ConfigurationData
	toSerialize["apiVersionId"] = o.ApiVersionId
	toSerialize["groupId"] = o.GroupId
	toSerialize["assetId"] = o.AssetId
	toSerialize["assetVersion"] = o.AssetVersion
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	toSerialize["upstreamIds"] = o.UpstreamIds
	return toSerialize, nil
}

func (o *ApimOutboundPolicyBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"configurationData",
		"apiVersionId",
		"groupId",
		"assetId",
		"assetVersion",
		"upstreamIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApimOutboundPolicyBody := _ApimOutboundPolicyBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApimOutboundPolicyBody)

	if err != nil {
		return err
	}

	*o = ApimOutboundPolicyBody(varApimOutboundPolicyBody)

	return err
}

type NullableApimOutboundPolicyBody struct {
	value *ApimOutboundPolicyBody
	isSet bool
}

func (v NullableApimOutboundPolicyBody) Get() *ApimOutboundPolicyBody {
	return v.value
}

func (v *NullableApimOutboundPolicyBody) Set(val *ApimOutboundPolicyBody) {
	v.value = val
	v.isSet = true
}

func (v NullableApimOutboundPolicyBody) IsSet() bool {
	return v.isSet
}

func (v *NullableApimOutboundPolicyBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApimOutboundPolicyBody(val *ApimOutboundPolicyBody) *NullableApimOutboundPolicyBody {
	return &NullableApimOutboundPolicyBody{value: val, isSet: true}
}

func (v NullableApimOutboundPolicyBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApimOutboundPolicyBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


