/*
Private Space API

Description of the Private Space API

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package private_space

import (
	"encoding/json"
)

// checks if the PrivateSpaceVpnConnectionPatchBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateSpaceVpnConnectionPatchBody{}

// PrivateSpaceVpnConnectionPatchBody Patch body for renaming an existing VPN connection.
type PrivateSpaceVpnConnectionPatchBody struct {
	// New display name for the VPN connection.
	Name *string `json:"name,omitempty"`
}

// NewPrivateSpaceVpnConnectionPatchBody instantiates a new PrivateSpaceVpnConnectionPatchBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateSpaceVpnConnectionPatchBody() *PrivateSpaceVpnConnectionPatchBody {
	this := PrivateSpaceVpnConnectionPatchBody{}
	return &this
}

// NewPrivateSpaceVpnConnectionPatchBodyWithDefaults instantiates a new PrivateSpaceVpnConnectionPatchBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateSpaceVpnConnectionPatchBodyWithDefaults() *PrivateSpaceVpnConnectionPatchBody {
	this := PrivateSpaceVpnConnectionPatchBody{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PrivateSpaceVpnConnectionPatchBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateSpaceVpnConnectionPatchBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PrivateSpaceVpnConnectionPatchBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PrivateSpaceVpnConnectionPatchBody) SetName(v string) {
	o.Name = &v
}

func (o PrivateSpaceVpnConnectionPatchBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateSpaceVpnConnectionPatchBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullablePrivateSpaceVpnConnectionPatchBody struct {
	value *PrivateSpaceVpnConnectionPatchBody
	isSet bool
}

func (v NullablePrivateSpaceVpnConnectionPatchBody) Get() *PrivateSpaceVpnConnectionPatchBody {
	return v.value
}

func (v *NullablePrivateSpaceVpnConnectionPatchBody) Set(val *PrivateSpaceVpnConnectionPatchBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateSpaceVpnConnectionPatchBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateSpaceVpnConnectionPatchBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateSpaceVpnConnectionPatchBody(val *PrivateSpaceVpnConnectionPatchBody) *NullablePrivateSpaceVpnConnectionPatchBody {
	return &NullablePrivateSpaceVpnConnectionPatchBody{value: val, isSet: true}
}

func (v NullablePrivateSpaceVpnConnectionPatchBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateSpaceVpnConnectionPatchBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


