/*
Private Space API

Description of the Private Space API

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package private_space

import (
	"encoding/json"
)

// checks if the PrivateSpaceSummaryPageableSort type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateSpaceSummaryPageableSort{}

// PrivateSpaceSummaryPageableSort struct for PrivateSpaceSummaryPageableSort
type PrivateSpaceSummaryPageableSort struct {
	Empty *bool `json:"empty,omitempty"`
	Sorted *bool `json:"sorted,omitempty"`
	Unsorted *bool `json:"unsorted,omitempty"`
}

// NewPrivateSpaceSummaryPageableSort instantiates a new PrivateSpaceSummaryPageableSort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateSpaceSummaryPageableSort() *PrivateSpaceSummaryPageableSort {
	this := PrivateSpaceSummaryPageableSort{}
	return &this
}

// NewPrivateSpaceSummaryPageableSortWithDefaults instantiates a new PrivateSpaceSummaryPageableSort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateSpaceSummaryPageableSortWithDefaults() *PrivateSpaceSummaryPageableSort {
	this := PrivateSpaceSummaryPageableSort{}
	return &this
}

// GetEmpty returns the Empty field value if set, zero value otherwise.
func (o *PrivateSpaceSummaryPageableSort) GetEmpty() bool {
	if o == nil || IsNil(o.Empty) {
		var ret bool
		return ret
	}
	return *o.Empty
}

// GetEmptyOk returns a tuple with the Empty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateSpaceSummaryPageableSort) GetEmptyOk() (*bool, bool) {
	if o == nil || IsNil(o.Empty) {
		return nil, false
	}
	return o.Empty, true
}

// HasEmpty returns a boolean if a field has been set.
func (o *PrivateSpaceSummaryPageableSort) HasEmpty() bool {
	if o != nil && !IsNil(o.Empty) {
		return true
	}

	return false
}

// SetEmpty gets a reference to the given bool and assigns it to the Empty field.
func (o *PrivateSpaceSummaryPageableSort) SetEmpty(v bool) {
	o.Empty = &v
}

// GetSorted returns the Sorted field value if set, zero value otherwise.
func (o *PrivateSpaceSummaryPageableSort) GetSorted() bool {
	if o == nil || IsNil(o.Sorted) {
		var ret bool
		return ret
	}
	return *o.Sorted
}

// GetSortedOk returns a tuple with the Sorted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateSpaceSummaryPageableSort) GetSortedOk() (*bool, bool) {
	if o == nil || IsNil(o.Sorted) {
		return nil, false
	}
	return o.Sorted, true
}

// HasSorted returns a boolean if a field has been set.
func (o *PrivateSpaceSummaryPageableSort) HasSorted() bool {
	if o != nil && !IsNil(o.Sorted) {
		return true
	}

	return false
}

// SetSorted gets a reference to the given bool and assigns it to the Sorted field.
func (o *PrivateSpaceSummaryPageableSort) SetSorted(v bool) {
	o.Sorted = &v
}

// GetUnsorted returns the Unsorted field value if set, zero value otherwise.
func (o *PrivateSpaceSummaryPageableSort) GetUnsorted() bool {
	if o == nil || IsNil(o.Unsorted) {
		var ret bool
		return ret
	}
	return *o.Unsorted
}

// GetUnsortedOk returns a tuple with the Unsorted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateSpaceSummaryPageableSort) GetUnsortedOk() (*bool, bool) {
	if o == nil || IsNil(o.Unsorted) {
		return nil, false
	}
	return o.Unsorted, true
}

// HasUnsorted returns a boolean if a field has been set.
func (o *PrivateSpaceSummaryPageableSort) HasUnsorted() bool {
	if o != nil && !IsNil(o.Unsorted) {
		return true
	}

	return false
}

// SetUnsorted gets a reference to the given bool and assigns it to the Unsorted field.
func (o *PrivateSpaceSummaryPageableSort) SetUnsorted(v bool) {
	o.Unsorted = &v
}

func (o PrivateSpaceSummaryPageableSort) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateSpaceSummaryPageableSort) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Empty) {
		toSerialize["empty"] = o.Empty
	}
	if !IsNil(o.Sorted) {
		toSerialize["sorted"] = o.Sorted
	}
	if !IsNil(o.Unsorted) {
		toSerialize["unsorted"] = o.Unsorted
	}
	return toSerialize, nil
}

type NullablePrivateSpaceSummaryPageableSort struct {
	value *PrivateSpaceSummaryPageableSort
	isSet bool
}

func (v NullablePrivateSpaceSummaryPageableSort) Get() *PrivateSpaceSummaryPageableSort {
	return v.value
}

func (v *NullablePrivateSpaceSummaryPageableSort) Set(val *PrivateSpaceSummaryPageableSort) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateSpaceSummaryPageableSort) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateSpaceSummaryPageableSort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateSpaceSummaryPageableSort(val *PrivateSpaceSummaryPageableSort) *NullablePrivateSpaceSummaryPageableSort {
	return &NullablePrivateSpaceSummaryPageableSort{value: val, isSet: true}
}

func (v NullablePrivateSpaceSummaryPageableSort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateSpaceSummaryPageableSort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


