/*
 * API Manager API
 *
 * API Manager API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// ApimInstancePatchResponse struct for ApimInstancePatchResponse
type ApimInstancePatchResponse struct {
	Audit *Audit `json:"audit,omitempty"`
	MasterOrganizationId *string `json:"masterOrganizationId,omitempty"`
	OrganizationId *string `json:"organizationId,omitempty"`
	Id *int32 `json:"id,omitempty"`
	InstanceLabel *string `json:"instanceLabel,omitempty"`
	ProviderId NullableString `json:"providerId,omitempty"`
	EndpointUri *string `json:"endpointUri,omitempty"`
	EnvironmentId *string `json:"environmentId,omitempty"`
	Technology *string `json:"technology,omitempty"`
	Routing *[]Routing `json:"routing,omitempty"`
	Endpoint *Endpoint `json:"endpoint,omitempty"`
	Deployment NullableDeployment `json:"deployment,omitempty"`
}

// NewApimInstancePatchResponse instantiates a new ApimInstancePatchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApimInstancePatchResponse() *ApimInstancePatchResponse {
	this := ApimInstancePatchResponse{}
	return &this
}

// NewApimInstancePatchResponseWithDefaults instantiates a new ApimInstancePatchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApimInstancePatchResponseWithDefaults() *ApimInstancePatchResponse {
	this := ApimInstancePatchResponse{}
	return &this
}

// GetAudit returns the Audit field value if set, zero value otherwise.
func (o *ApimInstancePatchResponse) GetAudit() Audit {
	if o == nil || o.Audit == nil {
		var ret Audit
		return ret
	}
	return *o.Audit
}

// GetAuditOk returns a tuple with the Audit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApimInstancePatchResponse) GetAuditOk() (*Audit, bool) {
	if o == nil || o.Audit == nil {
		return nil, false
	}
	return o.Audit, true
}

// HasAudit returns a boolean if a field has been set.
func (o *ApimInstancePatchResponse) HasAudit() bool {
	if o != nil && o.Audit != nil {
		return true
	}

	return false
}

// SetAudit gets a reference to the given Audit and assigns it to the Audit field.
func (o *ApimInstancePatchResponse) SetAudit(v Audit) {
	o.Audit = &v
}

// GetMasterOrganizationId returns the MasterOrganizationId field value if set, zero value otherwise.
func (o *ApimInstancePatchResponse) GetMasterOrganizationId() string {
	if o == nil || o.MasterOrganizationId == nil {
		var ret string
		return ret
	}
	return *o.MasterOrganizationId
}

// GetMasterOrganizationIdOk returns a tuple with the MasterOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApimInstancePatchResponse) GetMasterOrganizationIdOk() (*string, bool) {
	if o == nil || o.MasterOrganizationId == nil {
		return nil, false
	}
	return o.MasterOrganizationId, true
}

// HasMasterOrganizationId returns a boolean if a field has been set.
func (o *ApimInstancePatchResponse) HasMasterOrganizationId() bool {
	if o != nil && o.MasterOrganizationId != nil {
		return true
	}

	return false
}

// SetMasterOrganizationId gets a reference to the given string and assigns it to the MasterOrganizationId field.
func (o *ApimInstancePatchResponse) SetMasterOrganizationId(v string) {
	o.MasterOrganizationId = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *ApimInstancePatchResponse) GetOrganizationId() string {
	if o == nil || o.OrganizationId == nil {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApimInstancePatchResponse) GetOrganizationIdOk() (*string, bool) {
	if o == nil || o.OrganizationId == nil {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *ApimInstancePatchResponse) HasOrganizationId() bool {
	if o != nil && o.OrganizationId != nil {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *ApimInstancePatchResponse) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApimInstancePatchResponse) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApimInstancePatchResponse) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApimInstancePatchResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ApimInstancePatchResponse) SetId(v int32) {
	o.Id = &v
}

// GetInstanceLabel returns the InstanceLabel field value if set, zero value otherwise.
func (o *ApimInstancePatchResponse) GetInstanceLabel() string {
	if o == nil || o.InstanceLabel == nil {
		var ret string
		return ret
	}
	return *o.InstanceLabel
}

// GetInstanceLabelOk returns a tuple with the InstanceLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApimInstancePatchResponse) GetInstanceLabelOk() (*string, bool) {
	if o == nil || o.InstanceLabel == nil {
		return nil, false
	}
	return o.InstanceLabel, true
}

// HasInstanceLabel returns a boolean if a field has been set.
func (o *ApimInstancePatchResponse) HasInstanceLabel() bool {
	if o != nil && o.InstanceLabel != nil {
		return true
	}

	return false
}

// SetInstanceLabel gets a reference to the given string and assigns it to the InstanceLabel field.
func (o *ApimInstancePatchResponse) SetInstanceLabel(v string) {
	o.InstanceLabel = &v
}

// GetProviderId returns the ProviderId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApimInstancePatchResponse) GetProviderId() string {
	if o == nil || o.ProviderId.Get() == nil {
		var ret string
		return ret
	}
	return *o.ProviderId.Get()
}

// GetProviderIdOk returns a tuple with the ProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApimInstancePatchResponse) GetProviderIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ProviderId.Get(), o.ProviderId.IsSet()
}

// HasProviderId returns a boolean if a field has been set.
func (o *ApimInstancePatchResponse) HasProviderId() bool {
	if o != nil && o.ProviderId.IsSet() {
		return true
	}

	return false
}

// SetProviderId gets a reference to the given NullableString and assigns it to the ProviderId field.
func (o *ApimInstancePatchResponse) SetProviderId(v string) {
	o.ProviderId.Set(&v)
}
// SetProviderIdNil sets the value for ProviderId to be an explicit nil
func (o *ApimInstancePatchResponse) SetProviderIdNil() {
	o.ProviderId.Set(nil)
}

// UnsetProviderId ensures that no value is present for ProviderId, not even an explicit nil
func (o *ApimInstancePatchResponse) UnsetProviderId() {
	o.ProviderId.Unset()
}

// GetEndpointUri returns the EndpointUri field value if set, zero value otherwise.
func (o *ApimInstancePatchResponse) GetEndpointUri() string {
	if o == nil || o.EndpointUri == nil {
		var ret string
		return ret
	}
	return *o.EndpointUri
}

// GetEndpointUriOk returns a tuple with the EndpointUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApimInstancePatchResponse) GetEndpointUriOk() (*string, bool) {
	if o == nil || o.EndpointUri == nil {
		return nil, false
	}
	return o.EndpointUri, true
}

// HasEndpointUri returns a boolean if a field has been set.
func (o *ApimInstancePatchResponse) HasEndpointUri() bool {
	if o != nil && o.EndpointUri != nil {
		return true
	}

	return false
}

// SetEndpointUri gets a reference to the given string and assigns it to the EndpointUri field.
func (o *ApimInstancePatchResponse) SetEndpointUri(v string) {
	o.EndpointUri = &v
}

// GetEnvironmentId returns the EnvironmentId field value if set, zero value otherwise.
func (o *ApimInstancePatchResponse) GetEnvironmentId() string {
	if o == nil || o.EnvironmentId == nil {
		var ret string
		return ret
	}
	return *o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApimInstancePatchResponse) GetEnvironmentIdOk() (*string, bool) {
	if o == nil || o.EnvironmentId == nil {
		return nil, false
	}
	return o.EnvironmentId, true
}

// HasEnvironmentId returns a boolean if a field has been set.
func (o *ApimInstancePatchResponse) HasEnvironmentId() bool {
	if o != nil && o.EnvironmentId != nil {
		return true
	}

	return false
}

// SetEnvironmentId gets a reference to the given string and assigns it to the EnvironmentId field.
func (o *ApimInstancePatchResponse) SetEnvironmentId(v string) {
	o.EnvironmentId = &v
}

// GetTechnology returns the Technology field value if set, zero value otherwise.
func (o *ApimInstancePatchResponse) GetTechnology() string {
	if o == nil || o.Technology == nil {
		var ret string
		return ret
	}
	return *o.Technology
}

// GetTechnologyOk returns a tuple with the Technology field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApimInstancePatchResponse) GetTechnologyOk() (*string, bool) {
	if o == nil || o.Technology == nil {
		return nil, false
	}
	return o.Technology, true
}

// HasTechnology returns a boolean if a field has been set.
func (o *ApimInstancePatchResponse) HasTechnology() bool {
	if o != nil && o.Technology != nil {
		return true
	}

	return false
}

// SetTechnology gets a reference to the given string and assigns it to the Technology field.
func (o *ApimInstancePatchResponse) SetTechnology(v string) {
	o.Technology = &v
}

// GetRouting returns the Routing field value if set, zero value otherwise.
func (o *ApimInstancePatchResponse) GetRouting() []Routing {
	if o == nil || o.Routing == nil {
		var ret []Routing
		return ret
	}
	return *o.Routing
}

// GetRoutingOk returns a tuple with the Routing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApimInstancePatchResponse) GetRoutingOk() (*[]Routing, bool) {
	if o == nil || o.Routing == nil {
		return nil, false
	}
	return o.Routing, true
}

// HasRouting returns a boolean if a field has been set.
func (o *ApimInstancePatchResponse) HasRouting() bool {
	if o != nil && o.Routing != nil {
		return true
	}

	return false
}

// SetRouting gets a reference to the given []Routing and assigns it to the Routing field.
func (o *ApimInstancePatchResponse) SetRouting(v []Routing) {
	o.Routing = &v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *ApimInstancePatchResponse) GetEndpoint() Endpoint {
	if o == nil || o.Endpoint == nil {
		var ret Endpoint
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApimInstancePatchResponse) GetEndpointOk() (*Endpoint, bool) {
	if o == nil || o.Endpoint == nil {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *ApimInstancePatchResponse) HasEndpoint() bool {
	if o != nil && o.Endpoint != nil {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given Endpoint and assigns it to the Endpoint field.
func (o *ApimInstancePatchResponse) SetEndpoint(v Endpoint) {
	o.Endpoint = &v
}

// GetDeployment returns the Deployment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApimInstancePatchResponse) GetDeployment() Deployment {
	if o == nil || o.Deployment.Get() == nil {
		var ret Deployment
		return ret
	}
	return *o.Deployment.Get()
}

// GetDeploymentOk returns a tuple with the Deployment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApimInstancePatchResponse) GetDeploymentOk() (*Deployment, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Deployment.Get(), o.Deployment.IsSet()
}

// HasDeployment returns a boolean if a field has been set.
func (o *ApimInstancePatchResponse) HasDeployment() bool {
	if o != nil && o.Deployment.IsSet() {
		return true
	}

	return false
}

// SetDeployment gets a reference to the given NullableDeployment and assigns it to the Deployment field.
func (o *ApimInstancePatchResponse) SetDeployment(v Deployment) {
	o.Deployment.Set(&v)
}
// SetDeploymentNil sets the value for Deployment to be an explicit nil
func (o *ApimInstancePatchResponse) SetDeploymentNil() {
	o.Deployment.Set(nil)
}

// UnsetDeployment ensures that no value is present for Deployment, not even an explicit nil
func (o *ApimInstancePatchResponse) UnsetDeployment() {
	o.Deployment.Unset()
}

func (o ApimInstancePatchResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Audit != nil {
		toSerialize["audit"] = o.Audit
	}
	if o.MasterOrganizationId != nil {
		toSerialize["masterOrganizationId"] = o.MasterOrganizationId
	}
	if o.OrganizationId != nil {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.InstanceLabel != nil {
		toSerialize["instanceLabel"] = o.InstanceLabel
	}
	if o.ProviderId.IsSet() {
		toSerialize["providerId"] = o.ProviderId.Get()
	}
	if o.EndpointUri != nil {
		toSerialize["endpointUri"] = o.EndpointUri
	}
	if o.EnvironmentId != nil {
		toSerialize["environmentId"] = o.EnvironmentId
	}
	if o.Technology != nil {
		toSerialize["technology"] = o.Technology
	}
	if o.Routing != nil {
		toSerialize["routing"] = o.Routing
	}
	if o.Endpoint != nil {
		toSerialize["endpoint"] = o.Endpoint
	}
	if o.Deployment.IsSet() {
		toSerialize["deployment"] = o.Deployment.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableApimInstancePatchResponse struct {
	value *ApimInstancePatchResponse
	isSet bool
}

func (v NullableApimInstancePatchResponse) Get() *ApimInstancePatchResponse {
	return v.value
}

func (v *NullableApimInstancePatchResponse) Set(val *ApimInstancePatchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApimInstancePatchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApimInstancePatchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApimInstancePatchResponse(val *ApimInstancePatchResponse) *NullableApimInstancePatchResponse {
	return &NullableApimInstancePatchResponse{value: val, isSet: true}
}

func (v NullableApimInstancePatchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApimInstancePatchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


