/*
Role API

Testing DefaultApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package role

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/mulesoft-anypoint/anypoint-client-go/role"
)

func Test_role_DefaultApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultApiService OrganizationsOrgIdRolegroupsRolegroupIdRolesDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var rolegroupId string

		resp, httpRes, err := apiClient.DefaultApi.OrganizationsOrgIdRolegroupsRolegroupIdRolesDelete(context.Background(), orgId, rolegroupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrganizationsOrgIdRolegroupsRolegroupIdRolesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var rolegroupId string

		resp, httpRes, err := apiClient.DefaultApi.OrganizationsOrgIdRolegroupsRolegroupIdRolesGet(context.Background(), orgId, rolegroupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrganizationsOrgIdRolegroupsRolegroupIdRolesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var rolegroupId string

		resp, httpRes, err := apiClient.DefaultApi.OrganizationsOrgIdRolegroupsRolegroupIdRolesPost(context.Background(), orgId, rolegroupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService RolesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultApi.RolesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
