/*
Anypoint MQ specfication

Anypoint MQ API specification

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amq

import (
	"encoding/json"
)

// checks if the Queue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Queue{}

// Queue struct for Queue
type Queue struct {
	QueueId *string `json:"queueId,omitempty"`
	ExchangeId *string `json:"exchangeId,omitempty"`
	DefaultTtl *int32 `json:"defaultTtl,omitempty"`
	DefaultLockTtl *int32 `json:"defaultLockTtl,omitempty"`
	Type *string `json:"type,omitempty"`
	Encrypted *bool `json:"encrypted,omitempty"`
	DefaultDeliveryDelay *int32 `json:"defaultDeliveryDelay,omitempty"`
	DeadLetterQueueId *string `json:"deadLetterQueueId,omitempty"`
	MaxDeliveries *int32 `json:"maxDeliveries,omitempty"`
	Fifo *bool `json:"fifo,omitempty"`
}

// NewQueue instantiates a new Queue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueue() *Queue {
	this := Queue{}
	return &this
}

// NewQueueWithDefaults instantiates a new Queue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueWithDefaults() *Queue {
	this := Queue{}
	return &this
}

// GetQueueId returns the QueueId field value if set, zero value otherwise.
func (o *Queue) GetQueueId() string {
	if o == nil || IsNil(o.QueueId) {
		var ret string
		return ret
	}
	return *o.QueueId
}

// GetQueueIdOk returns a tuple with the QueueId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Queue) GetQueueIdOk() (*string, bool) {
	if o == nil || IsNil(o.QueueId) {
		return nil, false
	}
	return o.QueueId, true
}

// HasQueueId returns a boolean if a field has been set.
func (o *Queue) HasQueueId() bool {
	if o != nil && !IsNil(o.QueueId) {
		return true
	}

	return false
}

// SetQueueId gets a reference to the given string and assigns it to the QueueId field.
func (o *Queue) SetQueueId(v string) {
	o.QueueId = &v
}

// GetExchangeId returns the ExchangeId field value if set, zero value otherwise.
func (o *Queue) GetExchangeId() string {
	if o == nil || IsNil(o.ExchangeId) {
		var ret string
		return ret
	}
	return *o.ExchangeId
}

// GetExchangeIdOk returns a tuple with the ExchangeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Queue) GetExchangeIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExchangeId) {
		return nil, false
	}
	return o.ExchangeId, true
}

// HasExchangeId returns a boolean if a field has been set.
func (o *Queue) HasExchangeId() bool {
	if o != nil && !IsNil(o.ExchangeId) {
		return true
	}

	return false
}

// SetExchangeId gets a reference to the given string and assigns it to the ExchangeId field.
func (o *Queue) SetExchangeId(v string) {
	o.ExchangeId = &v
}

// GetDefaultTtl returns the DefaultTtl field value if set, zero value otherwise.
func (o *Queue) GetDefaultTtl() int32 {
	if o == nil || IsNil(o.DefaultTtl) {
		var ret int32
		return ret
	}
	return *o.DefaultTtl
}

// GetDefaultTtlOk returns a tuple with the DefaultTtl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Queue) GetDefaultTtlOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultTtl) {
		return nil, false
	}
	return o.DefaultTtl, true
}

// HasDefaultTtl returns a boolean if a field has been set.
func (o *Queue) HasDefaultTtl() bool {
	if o != nil && !IsNil(o.DefaultTtl) {
		return true
	}

	return false
}

// SetDefaultTtl gets a reference to the given int32 and assigns it to the DefaultTtl field.
func (o *Queue) SetDefaultTtl(v int32) {
	o.DefaultTtl = &v
}

// GetDefaultLockTtl returns the DefaultLockTtl field value if set, zero value otherwise.
func (o *Queue) GetDefaultLockTtl() int32 {
	if o == nil || IsNil(o.DefaultLockTtl) {
		var ret int32
		return ret
	}
	return *o.DefaultLockTtl
}

// GetDefaultLockTtlOk returns a tuple with the DefaultLockTtl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Queue) GetDefaultLockTtlOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultLockTtl) {
		return nil, false
	}
	return o.DefaultLockTtl, true
}

// HasDefaultLockTtl returns a boolean if a field has been set.
func (o *Queue) HasDefaultLockTtl() bool {
	if o != nil && !IsNil(o.DefaultLockTtl) {
		return true
	}

	return false
}

// SetDefaultLockTtl gets a reference to the given int32 and assigns it to the DefaultLockTtl field.
func (o *Queue) SetDefaultLockTtl(v int32) {
	o.DefaultLockTtl = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Queue) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Queue) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Queue) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Queue) SetType(v string) {
	o.Type = &v
}

// GetEncrypted returns the Encrypted field value if set, zero value otherwise.
func (o *Queue) GetEncrypted() bool {
	if o == nil || IsNil(o.Encrypted) {
		var ret bool
		return ret
	}
	return *o.Encrypted
}

// GetEncryptedOk returns a tuple with the Encrypted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Queue) GetEncryptedOk() (*bool, bool) {
	if o == nil || IsNil(o.Encrypted) {
		return nil, false
	}
	return o.Encrypted, true
}

// HasEncrypted returns a boolean if a field has been set.
func (o *Queue) HasEncrypted() bool {
	if o != nil && !IsNil(o.Encrypted) {
		return true
	}

	return false
}

// SetEncrypted gets a reference to the given bool and assigns it to the Encrypted field.
func (o *Queue) SetEncrypted(v bool) {
	o.Encrypted = &v
}

// GetDefaultDeliveryDelay returns the DefaultDeliveryDelay field value if set, zero value otherwise.
func (o *Queue) GetDefaultDeliveryDelay() int32 {
	if o == nil || IsNil(o.DefaultDeliveryDelay) {
		var ret int32
		return ret
	}
	return *o.DefaultDeliveryDelay
}

// GetDefaultDeliveryDelayOk returns a tuple with the DefaultDeliveryDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Queue) GetDefaultDeliveryDelayOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultDeliveryDelay) {
		return nil, false
	}
	return o.DefaultDeliveryDelay, true
}

// HasDefaultDeliveryDelay returns a boolean if a field has been set.
func (o *Queue) HasDefaultDeliveryDelay() bool {
	if o != nil && !IsNil(o.DefaultDeliveryDelay) {
		return true
	}

	return false
}

// SetDefaultDeliveryDelay gets a reference to the given int32 and assigns it to the DefaultDeliveryDelay field.
func (o *Queue) SetDefaultDeliveryDelay(v int32) {
	o.DefaultDeliveryDelay = &v
}

// GetDeadLetterQueueId returns the DeadLetterQueueId field value if set, zero value otherwise.
func (o *Queue) GetDeadLetterQueueId() string {
	if o == nil || IsNil(o.DeadLetterQueueId) {
		var ret string
		return ret
	}
	return *o.DeadLetterQueueId
}

// GetDeadLetterQueueIdOk returns a tuple with the DeadLetterQueueId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Queue) GetDeadLetterQueueIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeadLetterQueueId) {
		return nil, false
	}
	return o.DeadLetterQueueId, true
}

// HasDeadLetterQueueId returns a boolean if a field has been set.
func (o *Queue) HasDeadLetterQueueId() bool {
	if o != nil && !IsNil(o.DeadLetterQueueId) {
		return true
	}

	return false
}

// SetDeadLetterQueueId gets a reference to the given string and assigns it to the DeadLetterQueueId field.
func (o *Queue) SetDeadLetterQueueId(v string) {
	o.DeadLetterQueueId = &v
}

// GetMaxDeliveries returns the MaxDeliveries field value if set, zero value otherwise.
func (o *Queue) GetMaxDeliveries() int32 {
	if o == nil || IsNil(o.MaxDeliveries) {
		var ret int32
		return ret
	}
	return *o.MaxDeliveries
}

// GetMaxDeliveriesOk returns a tuple with the MaxDeliveries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Queue) GetMaxDeliveriesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxDeliveries) {
		return nil, false
	}
	return o.MaxDeliveries, true
}

// HasMaxDeliveries returns a boolean if a field has been set.
func (o *Queue) HasMaxDeliveries() bool {
	if o != nil && !IsNil(o.MaxDeliveries) {
		return true
	}

	return false
}

// SetMaxDeliveries gets a reference to the given int32 and assigns it to the MaxDeliveries field.
func (o *Queue) SetMaxDeliveries(v int32) {
	o.MaxDeliveries = &v
}

// GetFifo returns the Fifo field value if set, zero value otherwise.
func (o *Queue) GetFifo() bool {
	if o == nil || IsNil(o.Fifo) {
		var ret bool
		return ret
	}
	return *o.Fifo
}

// GetFifoOk returns a tuple with the Fifo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Queue) GetFifoOk() (*bool, bool) {
	if o == nil || IsNil(o.Fifo) {
		return nil, false
	}
	return o.Fifo, true
}

// HasFifo returns a boolean if a field has been set.
func (o *Queue) HasFifo() bool {
	if o != nil && !IsNil(o.Fifo) {
		return true
	}

	return false
}

// SetFifo gets a reference to the given bool and assigns it to the Fifo field.
func (o *Queue) SetFifo(v bool) {
	o.Fifo = &v
}

func (o Queue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Queue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.QueueId) {
		toSerialize["queueId"] = o.QueueId
	}
	if !IsNil(o.ExchangeId) {
		toSerialize["exchangeId"] = o.ExchangeId
	}
	if !IsNil(o.DefaultTtl) {
		toSerialize["defaultTtl"] = o.DefaultTtl
	}
	if !IsNil(o.DefaultLockTtl) {
		toSerialize["defaultLockTtl"] = o.DefaultLockTtl
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Encrypted) {
		toSerialize["encrypted"] = o.Encrypted
	}
	if !IsNil(o.DefaultDeliveryDelay) {
		toSerialize["defaultDeliveryDelay"] = o.DefaultDeliveryDelay
	}
	if !IsNil(o.DeadLetterQueueId) {
		toSerialize["deadLetterQueueId"] = o.DeadLetterQueueId
	}
	if !IsNil(o.MaxDeliveries) {
		toSerialize["maxDeliveries"] = o.MaxDeliveries
	}
	if !IsNil(o.Fifo) {
		toSerialize["fifo"] = o.Fifo
	}
	return toSerialize, nil
}

type NullableQueue struct {
	value *Queue
	isSet bool
}

func (v NullableQueue) Get() *Queue {
	return v.value
}

func (v *NullableQueue) Set(val *Queue) {
	v.value = val
	v.isSet = true
}

func (v NullableQueue) IsSet() bool {
	return v.isSet
}

func (v *NullableQueue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueue(val *Queue) *NullableQueue {
	return &NullableQueue{value: val, isSet: true}
}

func (v NullableQueue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


