/*
VPN API

Testing DefaultApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vpn

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/mulesoft-anypoint/anypoint-client-go/vpn"
)

func Test_vpn_DefaultApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultApiService OrganizationsOrgIdVpcsVpcIdIpsecGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var vpcId string

		resp, httpRes, err := apiClient.DefaultApi.OrganizationsOrgIdVpcsVpcIdIpsecGet(context.Background(), orgId, vpcId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrganizationsOrgIdVpcsVpcIdIpsecPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var vpcId string

		resp, httpRes, err := apiClient.DefaultApi.OrganizationsOrgIdVpcsVpcIdIpsecPost(context.Background(), orgId, vpcId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrganizationsOrgIdVpcsVpcIdIpsecVpnIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var vpcId string
		var vpnId string

		httpRes, err := apiClient.DefaultApi.OrganizationsOrgIdVpcsVpcIdIpsecVpnIdDelete(context.Background(), orgId, vpcId, vpnId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrganizationsOrgIdVpcsVpcIdIpsecVpnIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var vpcId string
		var vpnId string

		resp, httpRes, err := apiClient.DefaultApi.OrganizationsOrgIdVpcsVpcIdIpsecVpnIdGet(context.Background(), orgId, vpcId, vpnId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
