/*
 * Identity Provider Management API
 *
 * Description of Identity Provider API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package idp

import (
	"encoding/json"
)

// ClaimsMapping2 struct for ClaimsMapping2
type ClaimsMapping2 struct {
	// Field name in the SAML AttributeStatements that maps to username. By default, the NameID attribute in the SAML assertion is used.
	UsernameAttribute *string `json:"username_attribute,omitempty"`
	// Field name in the SAML AttributeStatements that maps to First Name. By default, the firstname attribute in the SAML assertion is used.
	FirstnameAttribute *string `json:"firstname_attribute,omitempty"`
	// Field name in the SAML AttributeStatements that maps to Last Name. By default, the lastname attribute in the SAML assertion is used.
	LastnameAttribute *string `json:"lastname_attribute,omitempty"`
	// Field name in the SAML AttributeStatements that maps to Email. By default, the email attribute in the SAML assertion is used.
	EmailAttribute *string `json:"email_attribute,omitempty"`
	// Field name in the SAML AttributeStatements that maps to Group.
	GroupAttribute *string `json:"group_attribute,omitempty"`
}

// NewClaimsMapping2 instantiates a new ClaimsMapping2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClaimsMapping2() *ClaimsMapping2 {
	this := ClaimsMapping2{}
	return &this
}

// NewClaimsMapping2WithDefaults instantiates a new ClaimsMapping2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClaimsMapping2WithDefaults() *ClaimsMapping2 {
	this := ClaimsMapping2{}
	return &this
}

// GetUsernameAttribute returns the UsernameAttribute field value if set, zero value otherwise.
func (o *ClaimsMapping2) GetUsernameAttribute() string {
	if o == nil || o.UsernameAttribute == nil {
		var ret string
		return ret
	}
	return *o.UsernameAttribute
}

// GetUsernameAttributeOk returns a tuple with the UsernameAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClaimsMapping2) GetUsernameAttributeOk() (*string, bool) {
	if o == nil || o.UsernameAttribute == nil {
		return nil, false
	}
	return o.UsernameAttribute, true
}

// HasUsernameAttribute returns a boolean if a field has been set.
func (o *ClaimsMapping2) HasUsernameAttribute() bool {
	if o != nil && o.UsernameAttribute != nil {
		return true
	}

	return false
}

// SetUsernameAttribute gets a reference to the given string and assigns it to the UsernameAttribute field.
func (o *ClaimsMapping2) SetUsernameAttribute(v string) {
	o.UsernameAttribute = &v
}

// GetFirstnameAttribute returns the FirstnameAttribute field value if set, zero value otherwise.
func (o *ClaimsMapping2) GetFirstnameAttribute() string {
	if o == nil || o.FirstnameAttribute == nil {
		var ret string
		return ret
	}
	return *o.FirstnameAttribute
}

// GetFirstnameAttributeOk returns a tuple with the FirstnameAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClaimsMapping2) GetFirstnameAttributeOk() (*string, bool) {
	if o == nil || o.FirstnameAttribute == nil {
		return nil, false
	}
	return o.FirstnameAttribute, true
}

// HasFirstnameAttribute returns a boolean if a field has been set.
func (o *ClaimsMapping2) HasFirstnameAttribute() bool {
	if o != nil && o.FirstnameAttribute != nil {
		return true
	}

	return false
}

// SetFirstnameAttribute gets a reference to the given string and assigns it to the FirstnameAttribute field.
func (o *ClaimsMapping2) SetFirstnameAttribute(v string) {
	o.FirstnameAttribute = &v
}

// GetLastnameAttribute returns the LastnameAttribute field value if set, zero value otherwise.
func (o *ClaimsMapping2) GetLastnameAttribute() string {
	if o == nil || o.LastnameAttribute == nil {
		var ret string
		return ret
	}
	return *o.LastnameAttribute
}

// GetLastnameAttributeOk returns a tuple with the LastnameAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClaimsMapping2) GetLastnameAttributeOk() (*string, bool) {
	if o == nil || o.LastnameAttribute == nil {
		return nil, false
	}
	return o.LastnameAttribute, true
}

// HasLastnameAttribute returns a boolean if a field has been set.
func (o *ClaimsMapping2) HasLastnameAttribute() bool {
	if o != nil && o.LastnameAttribute != nil {
		return true
	}

	return false
}

// SetLastnameAttribute gets a reference to the given string and assigns it to the LastnameAttribute field.
func (o *ClaimsMapping2) SetLastnameAttribute(v string) {
	o.LastnameAttribute = &v
}

// GetEmailAttribute returns the EmailAttribute field value if set, zero value otherwise.
func (o *ClaimsMapping2) GetEmailAttribute() string {
	if o == nil || o.EmailAttribute == nil {
		var ret string
		return ret
	}
	return *o.EmailAttribute
}

// GetEmailAttributeOk returns a tuple with the EmailAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClaimsMapping2) GetEmailAttributeOk() (*string, bool) {
	if o == nil || o.EmailAttribute == nil {
		return nil, false
	}
	return o.EmailAttribute, true
}

// HasEmailAttribute returns a boolean if a field has been set.
func (o *ClaimsMapping2) HasEmailAttribute() bool {
	if o != nil && o.EmailAttribute != nil {
		return true
	}

	return false
}

// SetEmailAttribute gets a reference to the given string and assigns it to the EmailAttribute field.
func (o *ClaimsMapping2) SetEmailAttribute(v string) {
	o.EmailAttribute = &v
}

// GetGroupAttribute returns the GroupAttribute field value if set, zero value otherwise.
func (o *ClaimsMapping2) GetGroupAttribute() string {
	if o == nil || o.GroupAttribute == nil {
		var ret string
		return ret
	}
	return *o.GroupAttribute
}

// GetGroupAttributeOk returns a tuple with the GroupAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClaimsMapping2) GetGroupAttributeOk() (*string, bool) {
	if o == nil || o.GroupAttribute == nil {
		return nil, false
	}
	return o.GroupAttribute, true
}

// HasGroupAttribute returns a boolean if a field has been set.
func (o *ClaimsMapping2) HasGroupAttribute() bool {
	if o != nil && o.GroupAttribute != nil {
		return true
	}

	return false
}

// SetGroupAttribute gets a reference to the given string and assigns it to the GroupAttribute field.
func (o *ClaimsMapping2) SetGroupAttribute(v string) {
	o.GroupAttribute = &v
}

func (o ClaimsMapping2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UsernameAttribute != nil {
		toSerialize["username_attribute"] = o.UsernameAttribute
	}
	if o.FirstnameAttribute != nil {
		toSerialize["firstname_attribute"] = o.FirstnameAttribute
	}
	if o.LastnameAttribute != nil {
		toSerialize["lastname_attribute"] = o.LastnameAttribute
	}
	if o.EmailAttribute != nil {
		toSerialize["email_attribute"] = o.EmailAttribute
	}
	if o.GroupAttribute != nil {
		toSerialize["group_attribute"] = o.GroupAttribute
	}
	return json.Marshal(toSerialize)
}

type NullableClaimsMapping2 struct {
	value *ClaimsMapping2
	isSet bool
}

func (v NullableClaimsMapping2) Get() *ClaimsMapping2 {
	return v.value
}

func (v *NullableClaimsMapping2) Set(val *ClaimsMapping2) {
	v.value = val
	v.isSet = true
}

func (v NullableClaimsMapping2) IsSet() bool {
	return v.isSet
}

func (v *NullableClaimsMapping2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClaimsMapping2(val *ClaimsMapping2) *NullableClaimsMapping2 {
	return &NullableClaimsMapping2{value: val, isSet: true}
}

func (v NullableClaimsMapping2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClaimsMapping2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


