/*
Connected App API

Description of the Connected App API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connected_app

import (
	"encoding/json"
)

// checks if the GetConnectedAppScopes200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetConnectedAppScopes200Response{}

// GetConnectedAppScopes200Response struct for GetConnectedAppScopes200Response
type GetConnectedAppScopes200Response struct {
	Data []ScopeCore `json:"data,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewGetConnectedAppScopes200Response instantiates a new GetConnectedAppScopes200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConnectedAppScopes200Response() *GetConnectedAppScopes200Response {
	this := GetConnectedAppScopes200Response{}
	return &this
}

// NewGetConnectedAppScopes200ResponseWithDefaults instantiates a new GetConnectedAppScopes200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConnectedAppScopes200ResponseWithDefaults() *GetConnectedAppScopes200Response {
	this := GetConnectedAppScopes200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetConnectedAppScopes200Response) GetData() []ScopeCore {
	if o == nil || IsNil(o.Data) {
		var ret []ScopeCore
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectedAppScopes200Response) GetDataOk() ([]ScopeCore, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetConnectedAppScopes200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ScopeCore and assigns it to the Data field.
func (o *GetConnectedAppScopes200Response) SetData(v []ScopeCore) {
	o.Data = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetConnectedAppScopes200Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectedAppScopes200Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetConnectedAppScopes200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetConnectedAppScopes200Response) SetTotal(v int32) {
	o.Total = &v
}

func (o GetConnectedAppScopes200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetConnectedAppScopes200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableGetConnectedAppScopes200Response struct {
	value *GetConnectedAppScopes200Response
	isSet bool
}

func (v NullableGetConnectedAppScopes200Response) Get() *GetConnectedAppScopes200Response {
	return v.value
}

func (v *NullableGetConnectedAppScopes200Response) Set(val *GetConnectedAppScopes200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConnectedAppScopes200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConnectedAppScopes200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConnectedAppScopes200Response(val *GetConnectedAppScopes200Response) *NullableGetConnectedAppScopes200Response {
	return &NullableGetConnectedAppScopes200Response{value: val, isSet: true}
}

func (v NullableGetConnectedAppScopes200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConnectedAppScopes200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


