/*
 * Organization API
 *
 * Description of the Organization API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package org

import (
	"encoding/json"
)

// TradingPartnersSandbox An explanation about the purpose of this instance.
type TradingPartnersSandbox struct {
	// An explanation about the purpose of this instance.
	Assigned int32 `json:"assigned"`
}

// NewTradingPartnersSandbox instantiates a new TradingPartnersSandbox object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTradingPartnersSandbox(assigned int32) *TradingPartnersSandbox {
	this := TradingPartnersSandbox{}
	this.Assigned = assigned
	return &this
}

// NewTradingPartnersSandboxWithDefaults instantiates a new TradingPartnersSandbox object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTradingPartnersSandboxWithDefaults() *TradingPartnersSandbox {
	this := TradingPartnersSandbox{}
	var assigned int32 = 0
	this.Assigned = assigned
	return &this
}

// GetAssigned returns the Assigned field value
func (o *TradingPartnersSandbox) GetAssigned() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Assigned
}

// GetAssignedOk returns a tuple with the Assigned field value
// and a boolean to check if the value has been set.
func (o *TradingPartnersSandbox) GetAssignedOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Assigned, true
}

// SetAssigned sets field value
func (o *TradingPartnersSandbox) SetAssigned(v int32) {
	o.Assigned = v
}

func (o TradingPartnersSandbox) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["assigned"] = o.Assigned
	}
	return json.Marshal(toSerialize)
}

type NullableTradingPartnersSandbox struct {
	value *TradingPartnersSandbox
	isSet bool
}

func (v NullableTradingPartnersSandbox) Get() *TradingPartnersSandbox {
	return v.value
}

func (v *NullableTradingPartnersSandbox) Set(val *TradingPartnersSandbox) {
	v.value = val
	v.isSet = true
}

func (v NullableTradingPartnersSandbox) IsSet() bool {
	return v.isSet
}

func (v *NullableTradingPartnersSandbox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTradingPartnersSandbox(val *TradingPartnersSandbox) *NullableTradingPartnersSandbox {
	return &NullableTradingPartnersSandbox{value: val, isSet: true}
}

func (v NullableTradingPartnersSandbox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTradingPartnersSandbox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


