/*
Organization API

Description of the Organization API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package org

import (
	"encoding/json"
)

// checks if the Exchange2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Exchange2{}

// Exchange2 An explanation about the purpose of this instance.
type Exchange2 struct {
	// An explanation about the purpose of this instance.
	Enabled bool `json:"enabled"`
}

// NewExchange2 instantiates a new Exchange2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExchange2(enabled bool) *Exchange2 {
	this := Exchange2{}
	this.Enabled = enabled
	return &this
}

// NewExchange2WithDefaults instantiates a new Exchange2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExchange2WithDefaults() *Exchange2 {
	this := Exchange2{}
	var enabled bool = false
	this.Enabled = enabled
	return &this
}

// GetEnabled returns the Enabled field value
func (o *Exchange2) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *Exchange2) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *Exchange2) SetEnabled(v bool) {
	o.Enabled = v
}

func (o Exchange2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Exchange2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	return toSerialize, nil
}

type NullableExchange2 struct {
	value *Exchange2
	isSet bool
}

func (v NullableExchange2) Get() *Exchange2 {
	return v.value
}

func (v *NullableExchange2) Set(val *Exchange2) {
	v.value = val
	v.isSet = true
}

func (v NullableExchange2) IsSet() bool {
	return v.isSet
}

func (v *NullableExchange2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExchange2(val *Exchange2) *NullableExchange2 {
	return &NullableExchange2{value: val, isSet: true}
}

func (v NullableExchange2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExchange2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


