/*
Runtime Fabrics API

Runtime Fabrics API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rtf

import (
	"encoding/json"
)

// checks if the FabricsUpgrade type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FabricsUpgrade{}

// FabricsUpgrade struct for FabricsUpgrade
type FabricsUpgrade struct {
	Status *string `json:"status,omitempty"`
}

// NewFabricsUpgrade instantiates a new FabricsUpgrade object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFabricsUpgrade() *FabricsUpgrade {
	this := FabricsUpgrade{}
	return &this
}

// NewFabricsUpgradeWithDefaults instantiates a new FabricsUpgrade object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFabricsUpgradeWithDefaults() *FabricsUpgrade {
	this := FabricsUpgrade{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *FabricsUpgrade) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FabricsUpgrade) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *FabricsUpgrade) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *FabricsUpgrade) SetStatus(v string) {
	o.Status = &v
}

func (o FabricsUpgrade) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FabricsUpgrade) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableFabricsUpgrade struct {
	value *FabricsUpgrade
	isSet bool
}

func (v NullableFabricsUpgrade) Get() *FabricsUpgrade {
	return v.value
}

func (v *NullableFabricsUpgrade) Set(val *FabricsUpgrade) {
	v.value = val
	v.isSet = true
}

func (v NullableFabricsUpgrade) IsSet() bool {
	return v.isSet
}

func (v *NullableFabricsUpgrade) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFabricsUpgrade(val *FabricsUpgrade) *NullableFabricsUpgrade {
	return &NullableFabricsUpgrade{value: val, isSet: true}
}

func (v NullableFabricsUpgrade) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFabricsUpgrade) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


