/*
User API

Description of the User API

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package user

import (
	"encoding/json"
)

// checks if the ListUsers200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListUsers200Response{}

// ListUsers200Response struct for ListUsers200Response
type ListUsers200Response struct {
	Data []User `json:"data,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewListUsers200Response instantiates a new ListUsers200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListUsers200Response() *ListUsers200Response {
	this := ListUsers200Response{}
	return &this
}

// NewListUsers200ResponseWithDefaults instantiates a new ListUsers200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListUsers200ResponseWithDefaults() *ListUsers200Response {
	this := ListUsers200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListUsers200Response) GetData() []User {
	if o == nil || IsNil(o.Data) {
		var ret []User
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListUsers200Response) GetDataOk() ([]User, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListUsers200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []User and assigns it to the Data field.
func (o *ListUsers200Response) SetData(v []User) {
	o.Data = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ListUsers200Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListUsers200Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ListUsers200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ListUsers200Response) SetTotal(v int32) {
	o.Total = &v
}

func (o ListUsers200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListUsers200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableListUsers200Response struct {
	value *ListUsers200Response
	isSet bool
}

func (v NullableListUsers200Response) Get() *ListUsers200Response {
	return v.value
}

func (v *NullableListUsers200Response) Set(val *ListUsers200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListUsers200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListUsers200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListUsers200Response(val *ListUsers200Response) *NullableListUsers200Response {
	return &NullableListUsers200Response{value: val, isSet: true}
}

func (v NullableListUsers200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListUsers200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


